# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Visite
    url: tour
    weight: 10
  - name: Nouvelles
    url: post
    weight: 20
  - name: Personnel
    url: people
    weight: 30
  - name: Evènements
    url: event
    weight: 40
  - name: Publications
    url: publication
    weight: 50
  - name: Mail et RDV
    url: contact
    weight: 60
