name = "Research Group"
license = "MIT"
licenselink = "https://github.com/wowchemy/starter-hugo-research-group/blob/main/LICENSE.md"
description = "The **Research Group Template** empowers your research group to easily create a beautiful website with a stunning homepage, news, academic publications, events, team profiles, and a contact form."
homepage = "https://github.com/wowchemy/starter-hugo-research-group"
demosite = "https://research-group.netlify.app/"
tags = ["association",
        "patients",
        "effets indésirables",
        "innovation",
        "sein",
        "orl",
        "cerveau",
        "thorax",
        "prostate",
        "rectum",
        "anal",
        "vessie",
        "pancreas",
        "col",
        "endometre",
        "metastase",
        "os",
        "sport",
        "douleur",
        "alimentation",
        "sommeil",
        "juridique",
        "social",
        "equipement",
        "medicament",
        "customizable",
        "technical",
        "slide"
        ]
features = ["page builder", "widgets", "themes", "search", "research publication system", "filterable portfolio",
            "blog", "create courses", "talks", "events", "slides", "gallery", "contact form"]

[author]
  name = ["Kevin Berthelot",
          "Marc Laurans",
          "Oana Cojocariu"
          ]
  homepage = "https://radiotherapie-sgl.netlify.app/"
